name: CI

on: [push]

jobs:
  build:
    env:
      CI: 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - run: yarn install
    - run: yarn build
    - run: yarn lint
    - run: yarn test
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: success() && github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
